[package]
name = "linux-listener-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
linux-listener-common = { path = "../linux-listener-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
network-types = "0.1.0"

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "linux-listener"
path = "src/main.rs"
