# Reference: https://docs.docker.com/reference/compose-file/
name: process-monitor

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "sleep infinity"
    container_name: devcontainer
    image: ubuntu:24.04
    volumes:
      - ..:/workspaces/process-monitor
    working_dir: /workspaces/process-monitor
