name: Build

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    name: Build application
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        arch: [arm64, amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set target triple
        if: ${{ runner.os == 'Windows' && matrix.arch == 'arm64' }}
        run: echo "CARGO_BUILD_TARGET=aarch64-pc-windows-msvc" >> "$env:GITHUB_ENV"

      - name: Set target triple
        if: ${{ runner.os == 'Windows' && matrix.arch == 'amd64' }}
        run: echo "CARGO_BUILD_TARGET=x86_64-pc-windows-msvc" >> "$env:GITHUB_ENV"

      - name: Set target triple
        if: ${{ runner.os == 'Linux' && matrix.arch == 'arm64' }}
        run: echo "CARGO_BUILD_TARGET=aarch64-unknown-linux-gnu" >> "$GITHUB_ENV"

      - name: Set target triple
        if: ${{ runner.os == 'Linux' && matrix.arch == 'amd64' }}
        run: echo "CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu" >> "$GITHUB_ENV"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91,nightly
          target: ${{ env.CARGO_BUILD_TARGET }}
          cache: false
          rustflags: ""

      - name: Add msbuild to PATH
        if: ${{ runner.os == 'Windows' }}
        uses: microsoft/setup-msbuild@v2

      - name: Setup tools
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          extern\wdksetup.exe /features + /log "%cd%\wdksetup.log" /quiet
          cargo install cargo-wdk

      - name: Setup tools
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev llvm
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          cargo install bpf-linker

      - name: Build Windows dynamic library
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        working-directory: windows-listener
        run: |
          cmd /c "cargo wdk build --profile release --target-arch ${{ matrix.arch }} || exit 0"
          tree /f

          if exist "target\${{ env.CARGO_BUILD_TARGET }}\release\windows_listener.dll" (
            if exist "target\${{ env.CARGO_BUILD_TARGET }}\release\windows_listener_driver_package" (
              exit 0
            )
          )

          exit 1

      - name: Build Linux dynamic library
        if: ${{ runner.os == 'Linux' }}
        working-directory: linux-listener
        run: cargo build --release --target ${{ env.CARGO_BUILD_TARGET }}

      - name: Build user-mode application
        run: |
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ --no-warn-unused-cli -S . -B build -G "MinGW Makefiles"
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ env.CARGO_BUILD_TARGET }}
          path: |
            wdksetup.log
            build/ProcessMonitorClient.exe
            windows-listener/target/${{ env.CARGO_BUILD_TARGET }}/release/windows_listener.dll
            windows-listener/target/${{ env.CARGO_BUILD_TARGET }}/release/windows_listener_driver_package
            linux-listener/target/${{ env.CARGO_BUILD_TARGET }}/release/liblinux_listener.so
