name: Build

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set target triple
        if: ${{ matrix.arch == 'arm64' }}
        run: echo "TARGET=aarch64-pc-windows-msvc" >> "$env:GITHUB_ENV"

      - name: Set target triple
        if: ${{ matrix.arch == 'amd64' }}
        run: echo "TARGET=x86_64-pc-windows-msvc" >> "$env:GITHUB_ENV"

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91,nightly
          target: ${{ env.TARGET }}
          cache: false
          rustflags: ""

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup tools
        shell: cmd
        run: |
          extern\wdksetup.exe /features + /log "%cd%\wdksetup.log" /quiet
          cargo install cargo-wdk

      - name: Build Windows dynamic library
        shell: cmd
        working-directory: windows-listener
        run: |
          cmd /c "cargo wdk build --profile release --target-arch ${{ matrix.arch }} || exit 0"

          if exist "target\${{ env.TARGET }}\release\windows_listener.dll" (
            echo "Found windows_listener.dll"
            if exist "target\${{ env.TARGET }}\release\windows_listener_driver_package" (
              echo "Found windows_listener_driver_package"

              mkdir target\release
              copy "target\${{ env.TARGET }}\release\windows_listener.dll" "target\release\"
              exit 0
            )
          )

          exit 1

      - name: Build user-mode application
        run: |
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ --no-warn-unused-cli -S . -B build -G "MinGW Makefiles"
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ env.TARGET }}
          path: |
            wdksetup.log
            build/CTA.exe
            build/CTB.exe
            windows-listener/target/${{ env.TARGET }}/release/windows_listener.dll
            windows-listener/target/${{ env.TARGET }}/release/windows_listener_driver_package

  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.91,nightly
          target: ${{ matrix.target }}
          cache: false
          rustflags: ""

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev llvm
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          cargo install bpf-linker

      - name: Build Linux dynamic library
        working-directory: linux-listener
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p target/release
          cp "target/${{ matrix.target }}/release/liblinux_listener.so" "target/release/"

      - name: Build user-mode application
        run: |
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ --no-warn-unused-cli -S . -B build
          cmake --build build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            wdksetup.log
            build/CTA
            build/CTB
            linux-listener/target/${{ matrix.target }}/release/liblinux_listener.so
